import type { AceToolConfig, ContextWeaverConfig } from '../types'
import fs from 'fs-extra'
import { homedir } from 'node:os'
import { join } from 'pathe'
import { parse as parseToml, stringify as stringifyToml } from 'smol-toml'

const CODEX_CONFIG_PATH = join(homedir(), '.codex', 'config.toml')

/**
 * Read Codex config.toml
 */
async function readCodexConfig(): Promise<Record<string, any>> {
  if (await fs.pathExists(CODEX_CONFIG_PATH)) {
    const content = await fs.readFile(CODEX_CONFIG_PATH, 'utf-8')
    return parseToml(content) as Record<string, any>
  }
  return {}
}

/**
 * Write Codex config.toml atomically (tmp + rename)
 */
async function writeCodexConfig(config: Record<string, any>): Promise<void> {
  const dir = join(homedir(), '.codex')
  await fs.ensureDir(dir)
  const tmpPath = `${CODEX_CONFIG_PATH}.tmp`
  await fs.writeFile(tmpPath, stringifyToml(config), 'utf-8')
  await fs.rename(tmpPath, CODEX_CONFIG_PATH)
}

/**
 * Install ace-tool MCP server to Codex config.toml
 */
export async function installAceTool(config: AceToolConfig): Promise<{ success: boolean, message: string }> {
  try {
    const codexConfig = await readCodexConfig()

    if (!codexConfig.mcp_servers) {
      codexConfig.mcp_servers = {}
    }

    const args = ['-y', 'ace-tool@latest']
    if (config.baseUrl) {
      args.push('--base-url', config.baseUrl)
    }
    if (config.token) {
      args.push('--token', config.token)
    }

    codexConfig.mcp_servers['ace-tool'] = {
      type: 'stdio',
      command: 'npx',
      args,
    }

    await writeCodexConfig(codexConfig)
    return { success: true, message: 'ace-tool MCP configured in ~/.codex/config.toml' }
  }
  catch (error) {
    return { success: false, message: `Failed to configure ace-tool: ${error}` }
  }
}

/**
 * Install ContextWeaver MCP server to Codex config.toml
 */
export async function installContextWeaver(config: ContextWeaverConfig): Promise<{ success: boolean, message: string }> {
  try {
    // Create ContextWeaver config directory and .env
    const contextWeaverDir = join(homedir(), '.contextweaver')
    await fs.ensureDir(contextWeaverDir)

    const envContent = `# ContextWeaver config (auto-generated by CXG)
EMBEDDINGS_API_KEY=${config.siliconflowApiKey}
EMBEDDINGS_BASE_URL=https://api.siliconflow.cn/v1/embeddings
EMBEDDINGS_MODEL=Qwen/Qwen3-Embedding-8B
EMBEDDINGS_MAX_CONCURRENCY=10
EMBEDDINGS_DIMENSIONS=1024
RERANK_API_KEY=${config.siliconflowApiKey}
RERANK_BASE_URL=https://api.siliconflow.cn/v1/rerank
RERANK_MODEL=Qwen/Qwen3-Reranker-8B
RERANK_TOP_N=20
`
    const envPath = join(contextWeaverDir, '.env')
    await fs.writeFile(envPath, envContent, { encoding: 'utf-8', mode: 0o600 })

    // Add to Codex config
    const codexConfig = await readCodexConfig()
    if (!codexConfig.mcp_servers) {
      codexConfig.mcp_servers = {}
    }

    codexConfig.mcp_servers.contextweaver = {
      type: 'stdio',
      command: 'contextweaver',
      args: ['mcp'],
    }

    await writeCodexConfig(codexConfig)
    return { success: true, message: 'ContextWeaver MCP configured in ~/.codex/config.toml' }
  }
  catch (error) {
    return { success: false, message: `Failed to configure ContextWeaver: ${error}` }
  }
}

/**
 * Uninstall an MCP server from Codex config.toml
 */
export async function uninstallMcpServer(id: string): Promise<{ success: boolean, message: string }> {
  try {
    const codexConfig = await readCodexConfig()
    if (codexConfig.mcp_servers?.[id]) {
      delete codexConfig.mcp_servers[id]
      await writeCodexConfig(codexConfig)
    }
    return { success: true, message: `${id} MCP removed from config` }
  }
  catch (error) {
    return { success: false, message: `Failed to uninstall ${id}: ${error}` }
  }
}
