import type { AceToolConfig, ContextWeaverConfig } from '../types'
import fs from 'fs-extra'
import { homedir } from 'node:os'
import { join } from 'pathe'
import { parse as parseToml, stringify as stringifyToml } from 'smol-toml'

function getCodexConfigPath(): string {
  return join(homedir(), '.codex', 'config.toml')
}

function readArgValue(args: unknown, key: string): string | undefined {
  if (!Array.isArray(args)) {
    return undefined
  }
  const index = args.findIndex(v => v === key)
  if (index < 0 || index + 1 >= args.length) {
    return undefined
  }
  const value = args[index + 1]
  return typeof value === 'string' ? value : undefined
}

function buildAceToolArgs(
  packageName: 'ace-tool' | 'ace-tool-rs',
  config: AceToolConfig,
  existingEntry?: Record<string, any>,
): string[] {
  const baseUrl = config.baseUrl || readArgValue(existingEntry?.args, '--base-url')
  const token = config.token || readArgValue(existingEntry?.args, '--token')

  const args = ['-y', `${packageName}@latest`]
  if (baseUrl) {
    args.push('--base-url', baseUrl)
  }
  if (token) {
    args.push('--token', token)
  }
  return args
}

/**
 * Read Codex config.toml
 */
async function readCodexConfig(): Promise<Record<string, any>> {
  const codexConfigPath = getCodexConfigPath()
  if (await fs.pathExists(codexConfigPath)) {
    const content = await fs.readFile(codexConfigPath, 'utf-8')
    return parseToml(content) as Record<string, any>
  }
  return {}
}

/**
 * Write Codex config.toml atomically (tmp + rename)
 */
async function writeCodexConfig(config: Record<string, any>): Promise<void> {
  const dir = join(homedir(), '.codex')
  await fs.ensureDir(dir)
  const codexConfigPath = getCodexConfigPath()
  const tmpPath = `${codexConfigPath}.tmp`
  await fs.writeFile(tmpPath, stringifyToml(config), 'utf-8')
  await fs.rename(tmpPath, codexConfigPath)
}

/**
 * Install ace-tool MCP server to Codex config.toml
 */
export async function installAceTool(config: AceToolConfig): Promise<{ success: boolean, message: string }> {
  try {
    const codexConfig = await readCodexConfig()

    if (!codexConfig.mcp_servers) {
      codexConfig.mcp_servers = {}
    }

    const args = buildAceToolArgs('ace-tool', config, codexConfig.mcp_servers['ace-tool'])

    codexConfig.mcp_servers['ace-tool'] = {
      type: 'stdio',
      command: 'npx',
      args,
    }

    await writeCodexConfig(codexConfig)
    return { success: true, message: 'ace-tool MCP configured in ~/.codex/config.toml' }
  }
  catch (error) {
    return { success: false, message: `Failed to configure ace-tool: ${error}` }
  }
}

/**
 * Install ContextWeaver MCP server to Codex config.toml
 */
export async function installContextWeaver(config: ContextWeaverConfig): Promise<{ success: boolean, message: string }> {
  try {
    // Create ContextWeaver config directory and .env
    const contextWeaverDir = join(homedir(), '.contextweaver')
    await fs.ensureDir(contextWeaverDir)

    const envContent = `# ContextWeaver config (auto-generated by CXG)
EMBEDDINGS_API_KEY=${config.siliconflowApiKey}
EMBEDDINGS_BASE_URL=https://api.siliconflow.cn/v1/embeddings
EMBEDDINGS_MODEL=Qwen/Qwen3-Embedding-8B
EMBEDDINGS_MAX_CONCURRENCY=10
EMBEDDINGS_DIMENSIONS=1024
RERANK_API_KEY=${config.siliconflowApiKey}
RERANK_BASE_URL=https://api.siliconflow.cn/v1/rerank
RERANK_MODEL=Qwen/Qwen3-Reranker-8B
RERANK_TOP_N=20
`
    const envPath = join(contextWeaverDir, '.env')
    await fs.writeFile(envPath, envContent, { encoding: 'utf-8', mode: 0o600 })

    // Add to Codex config
    const codexConfig = await readCodexConfig()
    if (!codexConfig.mcp_servers) {
      codexConfig.mcp_servers = {}
    }

    codexConfig.mcp_servers.contextweaver = {
      type: 'stdio',
      command: 'contextweaver',
      args: ['mcp'],
    }

    await writeCodexConfig(codexConfig)
    return { success: true, message: 'ContextWeaver MCP configured in ~/.codex/config.toml' }
  }
  catch (error) {
    return { success: false, message: `Failed to configure ContextWeaver: ${error}` }
  }
}

/**
 * Install ace-tool-rs MCP server to Codex config.toml
 */
export async function installAceToolRs(config: AceToolConfig): Promise<{ success: boolean, message: string }> {
  try {
    const codexConfig = await readCodexConfig()
    if (!codexConfig.mcp_servers) {
      codexConfig.mcp_servers = {}
    }

    const args = buildAceToolArgs('ace-tool-rs', config, codexConfig.mcp_servers['ace-tool'])

    codexConfig.mcp_servers['ace-tool'] = {
      type: 'stdio',
      command: 'npx',
      args,
    }

    await writeCodexConfig(codexConfig)
    return { success: true, message: 'ace-tool-rs MCP configured in ~/.codex/config.toml' }
  }
  catch (error) {
    return { success: false, message: `Failed to configure ace-tool-rs: ${error}` }
  }
}

/**
 * Install a generic MCP server to Codex config.toml
 */
export async function installMcpServer(
  id: string,
  command: string,
  args: string[],
  env: Record<string, string> = {},
): Promise<{ success: boolean, message: string }> {
  try {
    const codexConfig = await readCodexConfig()
    if (!codexConfig.mcp_servers) {
      codexConfig.mcp_servers = {}
    }

    const entry: Record<string, any> = { type: 'stdio', command, args }
    if (Object.keys(env).length > 0) {
      entry.env = env
    }

    codexConfig.mcp_servers[id] = entry
    await writeCodexConfig(codexConfig)
    return { success: true, message: `${id} MCP configured in ~/.codex/config.toml` }
  }
  catch (error) {
    return { success: false, message: `Failed to install ${id}: ${error}` }
  }
}

/**
 * Uninstall an MCP server from Codex config.toml
 */
export async function uninstallMcpServer(id: string): Promise<{ success: boolean, message: string }> {
  try {
    const codexConfig = await readCodexConfig()
    if (codexConfig.mcp_servers?.[id]) {
      delete codexConfig.mcp_servers[id]
      await writeCodexConfig(codexConfig)
    }
    return { success: true, message: `${id} MCP removed from config` }
  }
  catch (error) {
    return { success: false, message: `Failed to uninstall ${id}: ${error}` }
  }
}
